services:
  vodkand-backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
      - ./backend/.env.production
    volumes:
      - ./backend/uploads:/vodkandApp/uploads
    ports:
      - "5002:5000"

  vodkand-frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3002:80"
    depends_on:
      - vodkand-backend