name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/vodkandApp
            git pull origin main
            docker compose up -d --build